In [3]:
i=[1,2,3]
w=[0.2,0.8,-0.5]
bias=2

output=i[0]*w[0]+ i[1]*w[1]+ i[2]*w[2] + bias
print(output)

2.3


inputs can be from the different sensors or maybe ~from the previous layer's neurons~

In [4]:
i=[1,2,3,2.5]
w=[0.2,0.8,-0.5,1]
bias=2
output=i[0]*w[0]+ i[1]*w[1]+ i[2]*w[2] + i[3]*w[3] + bias
print(output)


4.8


modelling 3 neurons with 4 inputs

In [ ]:
i=[1,2,3,2.5]
w_e=[0.2,0.8,-0.5,1]
w_f=[0.5,-0.91,0.26,-0.5]
w_g=[-0.26,-0.27,0.17,0.87]
b_e=2
b_f=3
b_g=0.5
output=[i[0]*w_e[0]+ i[1]*w_e[1]+ i[2]*w_e[2] + i[3]*w_e[3] + b_e,
        i[0]*w_f[0]+ i[1]*w_f[1] + i[2]* w_f[2]+ i[3]* w_f[3]+ b_f,
        i[0]*w_g[0]+ i[1]*w_g[1] + i[2]* w_g[2]+ i[3]* w_g[3]+ b_g
]

print(output)

[4.8, 1.21, 2.385]


rather we use dot product(numpy)

In [2]:
import numpy as np

i=[1,2,3,2.5]

w=[[0.2,0.8,-0.5,1],
    [0.5,-0.91,0.26,-0.5],
    [-0.26,-0.27,0.17,0.87]]
b=[2,3,0.5]

output=np.dot(w,i)+b


print(output)

[4.8   1.21  2.385]


with batches of input

In [3]:
inputs=[[1,2,3,2.5],
        [2,5,-1,2],
        [-1.5,2.7,3.3,-0.8]]
weights=[[0.2,0.8,-0.5,1],
          [0.5,-0.91,0.26,-0.5],
          [-0.26,-0.27,0.17,0.87]]
biases=[2,3,0.5]
output=np.dot(inputs,np.array(weights).T)+biases
print(output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


incoreect format(wt,input)

In [5]:
inputs=[[1,2,3,2.5],
        [2,5,-1,2],
        [-1.5,2.7,3.3,-0.8]]
weights=[[0.2,0.8,-0.5,1],
          [0.5,-0.91,0.26,-0.5],
          [-0.26,-0.27,0.17,0.87]]
biases=[2,3,0.5]
output=np.dot(weights,np.array(inputs).T)+biases
print(output)

[[ 4.8    9.9   -0.09 ]
 [ 0.21  -1.81  -1.449]
 [ 3.885  2.7    0.026]]


add another layer

In [12]:
inputs=[[1,2,3,2.5],
        [2,5,-1,2],
        [-1.5,2.7,3.3,-0.8]]
weights1=[[0.2,0.8,-0.5,1],
          [0.5,-0.91,0.26,-0.5],
          [-0.26,-0.27,0.17,0.87]]
biases1=[2,3,0.5]
weights2=[[0.1,-0.14,0.5],
          [-0.5,0.12,-0.33],
          [-0.44,0.73,-0.13]]
biases2=[-1,2,-0.5]

l1_output=np.dot(inputs,np.array(weights1).T)+biases1
l2_output=np.dot(inputs,np.array(weights).T)+biases2
print('The outout from 1st layer is:\n',l1_output)
print('The outout from 2nd layer is:\n',l2_output)

The outout from 1st layer is:
 [[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
The outout from 2nd layer is:
 [[ 1.8    0.21   1.385]
 [ 5.9   -2.81  -0.8  ]
 [-1.59   0.051 -0.974]]


In [19]:
import numpy as np
np.random.seed(0)
X=[[1,2,3,2.5],
    [2,5,-1,2],
    [-1.5,2.7,3.3,-0.8]]

class Layer_Dense:
    def __init__(self,n_inputs,n_neurons):
        self.weights=0.10*np.random.randn(n_inputs,n_neurons)
        self.biases=np.zeros((1,n_neurons))
    def forward(self,inputs):

        self.output=np.dot(inputs,self.weights)+ self.biases

layer1=Layer_Dense(4,5)
layer2=Layer_Dense(5,2)

layer1.forward(X)

# print(layer1.output)
layer2.forward(layer1.output)
print(layer2.weights)
print(layer2.output)

[[-0.25529898  0.06536186]
 [ 0.08644362 -0.0742165 ]
 [ 0.22697546 -0.14543657]
 [ 0.00457585 -0.01871839]
 [ 0.15327792  0.14693588]]
[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]


activation functions



In [24]:
import numpy as np
import nnfs
nnfs.init()
from nnfs.datasets import spiral_data
np.random.seed(0)
# X=[[1,2,3,2.5],
#     [2,5,-1,2],
#     [-1.5,2.7,3.3,-0.8]]
X,y=spiral_data(100,3)
class Layer_Dense:
    def __init__(self,n_inputs,n_neurons):
        self.weights=0.10*np.random.randn(n_inputs,n_neurons)
        self.biases=np.zeros((1,n_neurons))
    def forward(self,inputs):
        self.output=np.dot(inputs,self.weights)+ self.biases
class Activation_ReLU:
    def forward(self,inputs):
        self.output=np.maximum(0,inputs)


layer1=Layer_Dense(2,5)
# acivation1=Activation_ReLU()
layer1.forward(X)
print(layer1.output)
activation1=Activation_ReLU()
activation1.forward(X)
print(activation1.output)

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [-8.35815910e-04 -7.90404272e-04 -1.33452227e-03  4.65504505e-04
   4.56846210e-05]
 [-2.39994470e-03  5.93469958e-05 -2.24808278e-03  2.03573116e-04
   6.10024377e-04]
 ...
 [ 1.13291524e-01 -1.89262271e-01 -2.06855070e-02  8.11079666e-02
  -6.71350807e-02]
 [ 1.34588361e-01 -1.43197834e-01  3.09493970e-02  5.66337556e-02
  -6.29687458e-02]
 [ 1.07817926e-01 -2.00809643e-01 -3.37579325e-02  8.72561932e-02
  -6.81458861e-02]]
[[0.00000000e+00 0.00000000e+00]
 [2.99555692e-03 9.64660756e-03]
 [1.28809698e-02 1.55628482e-02]
 [2.99747903e-02 4.44809627e-03]
 [3.93124595e-02 9.32828337e-03]
 [8.28829070e-04 5.04982509e-02]
 [5.34835160e-02 2.85062827e-02]
 [4.17361967e-02 5.70752136e-02]
 [5.54633923e-02 5.87686822e-02]
 [8.16038325e-02 4.00659069e-02]
 [8.91875103e-02 4.74197045e-02]
 [1.07160836e-01 0.00000000e+00]
 [1.21183202e-01 0.00000000e+00]
 [1.28777727e-01 2.56794747e-02]
 [1.41112968e-01 0.000

softmax

In [36]:
import math
layer_outputs=[4.8,1.21,2.385]
E=math.e
exp_values=[]
for output in layer_outputs:
    exp_values.append(E**output)
print(exp_values)

norm_base=sum(exp_values)
norm_values=[]
for values in exp_values:
    norm_values.append(values/norm_base)
print('The normalised values are: ',norm_values)
print('The summed value is: ',sum(norm_values))

[121.51041751873483, 3.353484652549023, 10.859062664920513]
The normalised values are:  [0.8952826639572619, 0.024708306782099374, 0.0800090292606387]
The summed value is:  0.9999999999999999


categorical cross-entropy


In [51]:
import math

softmax_output=[0.7,0.1,0.2]
target_class=[1,0,0]

loss = 0
for p, t in zip(softmax_output, target_class):
    loss += -t * math.log(p)

print(loss)



0.35667494393873245


In [56]:
import math

softmax_output=[0.7,0.1,0.2]
target_output=[1,0,0]
loss=-(math.log(softmax_output[0])*target_output[0]+
       math.log(softmax_output[1])*target_output[1]+
       math.log(softmax_output[2])*target_output[2]
        )
print(loss)
loss1=-math.log(softmax_output[0])
print(loss1)

0.35667494393873245
0.35667494393873245


In [70]:
import numpy as np
softmax_output=np.array([[0.7,0.1,0.2],
                        [0.1,0.5,0.4],
                        [0.02,0.9,0.08]])
class_targets=[0,1,1]
print(softmax_output[[0,1,2],class_targets])  #prints out softmax_output ko 0,1,2 row ko [0,1,1](class targets)index ma vako values


[0.7 0.5 0.9]


In [79]:
neg_log=-np.log(softmax_output[range(len(softmax_output)),class_targets])
print(neg_log)
print(sum(neg_log))

[0.35667494 0.69314718 0.10536052]
1.1551826401565042


-log(0)= infinite so we have problem here sooo...

In [83]:
import numpy as np
import nnfs
nnfs.init()
from nnfs.datasets import spiral_data
np.random.seed(0)

X, y = spiral_data(100, 3)

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

class Activation_Softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities

class Loss:
    def calculate(self, output, y):
        sample_losses = self.forward(output, y)
        data_loss = np.mean(sample_losses)
        return data_loss

class Loss_Categorical_Cross_entropy(Loss):
    def forward(self, y_pred, y_true):
        samples = len(y_pred)
        y_pred_clipped = np.clip(y_pred, 1e-7, 1-1e-7)

        # sparse labels
        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[range(samples), y_true]

        # one-hot labels
        elif len(y_true.shape) == 2:
            correct_confidences = np.sum(y_pred_clipped * y_true, axis=1)

        negative_log_likelihoods = -np.log(correct_confidences)
        return negative_log_likelihoods

# MODEL
layer1 = Layer_Dense(2, 5)
activation1 = Activation_ReLU()

# Forward pass
layer1.forward(X)
activation1.forward(layer1.output)

layer2 = Layer_Dense(5, 3)
activation2 = Activation_Softmax()

layer2.forward(activation1.output)
activation2.forward(layer2.output)
print(activation2.output[:5])
# Loss
loss_function = Loss_Categorical_Cross_entropy()
loss = loss_function.calculate(activation2.output, y)

print(loss)


[[0.33333334 0.33333334 0.33333334]
 [0.33334148 0.33333018 0.33332834]
 [0.33335316 0.33332598 0.3333209 ]
 [0.333332   0.3333076  0.3333604 ]
 [0.33333603 0.33330086 0.33336315]]
1.0988971
